---
title: "titanic"
author: "djaw"
date: "2024-11-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
library(carData)
df<-TitanicSurvival
summary(df)
plot(df$survived~df$sex, col=c("orange","lightgreen"))
plot(df$survived~df$passengerClass)
plot(df$age~df$survived)

library(ggplot2)
ggplot(df, aes(survived,fill=sex)) +
  geom_bar(position = "dodge",width = 0.4)+
  theme_minimal()
  ggplot(df, aes(passengerClass,fill=survived)) +
  geom_bar(position = "dodge",width = 0.3)+
  scale_fill_brewer(palette = "Blues")
  
  ggplot(df, aes(survived,age)) +
  geom_boxplot() +
  theme_minimal()
  
  y<-as.numeric(df$survived)-1
summary(glm(y~age+sex+passengerClass , data=df,family = binomial(link = "logit")))


#### TP Titanic packages

#' taux de survie en fonction du sex
#'
#' @param data data frame
#' @return A list
#' @examples
#' taux_survie_sex(df)
#' @export

taux_survie_sex <- function(data) {
  library(dplyr)
  return(data %>%
    group_by(sex) %>%
    summarize(TauxSurvie = sum(survived == "yes") / n()))
}




######################
######################

#' taux de survie en fonction de la classe
#' 
#' @author Bineta FAYE
#' @param data data frame
#' @return A list
#' @examples
#' taux_survie_class(df)
#' @export

taux_survie_class <- function(data) {
  library(dplyr)
  return(data %>%
           group_by(passengerClass) %>%
           summarize(TauxSurvie = sum(survived == "yes") / n()))
}


library(TitanicPckg)
## 
## Attachement du package : 'TitanicPckg'
## Les objets suivants sont masqués _par_ '.GlobalEnv':
## 
##     taux_survie_class, taux_survie_sex
taux_survie_sex(df)
## Warning: le package 'dplyr' a été compilé avec la version R 4.3.3
## 
## Attachement du package : 'dplyr'
## Les objets suivants sont masqués depuis 'package:stats':
## 
##     filter, lag
## Les objets suivants sont masqués depuis 'package:base':
## 
##     intersect, setdiff, setequal, union
## # A tibble: 2 × 2
##   sex    TauxSurvie
##   <fct>       <dbl>
## 1 female      0.727
## 2 male        0.191
TitanicPckg::taux_survie_class(df)
## # A tibble: 3 × 2
##   passengerClass TauxSurvie
##   <fct>               <dbl>
## 1 1st                 0.619
## 2 2nd                 0.430
## 3 3rd                 0.255